### ISSUE TITLE
Add @piks3l to https://tosdr.org/about.html#contact

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosdr-build#31]
Hi @piks3l, welcome to the team! Can you create a pull-request to add yourself to https://tosdr.org/about.html#contact? The file to edit is https://github.com/tosdr/tosdr-build/blob/master/src/about.html#L89 (you can either use github's online editor or clone the repo to your own computer and push a new branch with your change).

**Comment by piks3l** [comment]
Hi @michielbdejong ! I'm doing that tonight/tomorrow and will look up the code this week-end :) Cheers !
