### ISSUE TITLE
Link to feed broken

### ISSUE THREAD

**Issue by Ryuno-Ki** [tosdr/tosdr-build#94]
Hi,
today I wanted to subscribe to your blog. But the [link on the homepage](https://github.com/tosdr/tosdr-build/blob/b0314827206ea57aebb5e8b2f2e737fe33a42b5c/index-template.html#L96) is wrong. It is not https://tosdr.org/atom.xml/ but https://tosdr.org/blog/feed.rss see [source code](https://github.com/tosdr/tosdr-build/blob/master/src/blog/feed.rss#L13).

Would you accept a PR here?

**Comment by Vinnl** [comment]
Absolutely, thanks for spotting it - looking forward to a PR :)

**Comment by Vinnl** [comment]
@michielbdejong I want to deploy the current `master`, but the 5apps repository appears to be empty as a result of the latest commit (582a49752f40b60b782546dfb41acd2e39545b93) - although for some reason, it appears that 0d54d5d875773ad566ad4f6d210cd615eece8379 is the commit that has been deployed. I'm a bit hesitant to push the rebuilt website - is it safe to do so?

**Comment by michielbdejong** [comment]
Ouch, I saw that before, it happens when the build script encounters an error and doesn't finish populating the files. I will try to build and deploy now.

**Comment by Ryuno-Ki** [comment]
... so any action needed from my side?

**Comment by Vinnl** [comment]
@Ryuno-Ki No no worries, Michiel has a new laptop that needs to get set up, and hasn't touched this project in a while, that's why it's taking a bit longer :)
